name: Build Windows Only

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build-windows:
    name: Windows
    uses: ./.github/workflows/ci-windows.yml
    with:
      publish_release: 'false'
      release_commit: ${{ github.sha }}
      release_version: 'v0.0.0-pframe-fix'
